// Generated by gencpp from file light_service/Light_Set.msg
// DO NOT EDIT!


#ifndef LIGHT_SERVICE_MESSAGE_LIGHT_SET_H
#define LIGHT_SERVICE_MESSAGE_LIGHT_SET_H

#include <ros/service_traits.h>


#include <light_service/Light_SetRequest.h>
#include <light_service/Light_SetResponse.h>


namespace light_service
{

struct Light_Set
{

typedef Light_SetRequest Request;
typedef Light_SetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Light_Set
} // namespace light_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::light_service::Light_Set > {
  static const char* value()
  {
    return "cfc723b899523d9fb55d7d41b0cedf61";
  }

  static const char* value(const ::light_service::Light_Set&) { return value(); }
};

template<>
struct DataType< ::light_service::Light_Set > {
  static const char* value()
  {
    return "light_service/Light_Set";
  }

  static const char* value(const ::light_service::Light_Set&) { return value(); }
};


// service_traits::MD5Sum< ::light_service::Light_SetRequest> should match
// service_traits::MD5Sum< ::light_service::Light_Set >
template<>
struct MD5Sum< ::light_service::Light_SetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::light_service::Light_Set >::value();
  }
  static const char* value(const ::light_service::Light_SetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::light_service::Light_SetRequest> should match
// service_traits::DataType< ::light_service::Light_Set >
template<>
struct DataType< ::light_service::Light_SetRequest>
{
  static const char* value()
  {
    return DataType< ::light_service::Light_Set >::value();
  }
  static const char* value(const ::light_service::Light_SetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::light_service::Light_SetResponse> should match
// service_traits::MD5Sum< ::light_service::Light_Set >
template<>
struct MD5Sum< ::light_service::Light_SetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::light_service::Light_Set >::value();
  }
  static const char* value(const ::light_service::Light_SetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::light_service::Light_SetResponse> should match
// service_traits::DataType< ::light_service::Light_Set >
template<>
struct DataType< ::light_service::Light_SetResponse>
{
  static const char* value()
  {
    return DataType< ::light_service::Light_Set >::value();
  }
  static const char* value(const ::light_service::Light_SetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIGHT_SERVICE_MESSAGE_LIGHT_SET_H
