// Generated by gencpp from file light_service/Light_SetResponse.msg
// DO NOT EDIT!


#ifndef LIGHT_SERVICE_MESSAGE_LIGHT_SETRESPONSE_H
#define LIGHT_SERVICE_MESSAGE_LIGHT_SETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_service
{
template <class ContainerAllocator>
struct Light_SetResponse_
{
  typedef Light_SetResponse_<ContainerAllocator> Type;

  Light_SetResponse_()
    : result()  {
    }
  Light_SetResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::light_service::Light_SetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_service::Light_SetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Light_SetResponse_

typedef ::light_service::Light_SetResponse_<std::allocator<void> > Light_SetResponse;

typedef boost::shared_ptr< ::light_service::Light_SetResponse > Light_SetResponsePtr;
typedef boost::shared_ptr< ::light_service::Light_SetResponse const> Light_SetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_service::Light_SetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_service::Light_SetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::light_service::Light_SetResponse_<ContainerAllocator1> & lhs, const ::light_service::Light_SetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::light_service::Light_SetResponse_<ContainerAllocator1> & lhs, const ::light_service::Light_SetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace light_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::light_service::Light_SetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_service::Light_SetResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_service::Light_SetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_service::Light_SetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_service::Light_SetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_service::Light_SetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_service::Light_SetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::light_service::Light_SetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::light_service::Light_SetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_service/Light_SetResponse";
  }

  static const char* value(const ::light_service::Light_SetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_service::Light_SetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 服务器响应发送的数据\n"
"string result\n"
;
  }

  static const char* value(const ::light_service::Light_SetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_service::Light_SetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Light_SetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_service::Light_SetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_service::Light_SetResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_SERVICE_MESSAGE_LIGHT_SETRESPONSE_H
