(cl:defpackage skeleton_follow-msg
  (:use )
  (:export
   "<ASTRA_SDK_BODY>"
   "ASTRA_SDK_BODY"
   "<ASTRA_SDK_BODYATTITUDE>"
   "ASTRA_SDK_BODYATTITUDE"
   "<ASTRA_SDK_BODYNUMBER>"
   "ASTRA_SDK_BODYNUMBER"
   "<ASTRA_SDK_JOINT>"
   "ASTRA_SDK_JOINT"
   "<ASTRA_SDK_MASKDATA>"
   "ASTRA_SDK_MASKDATA"
   "<ASTRA_SDK_RGB>"
   "ASTRA_SDK_RGB"
   "<ASTRA_SDK_VECTOR2F>"
   "ASTRA_SDK_VECTOR2F"
   "<ASTRA_SDK_VECTOR3F>"
   "ASTRA_SDK_VECTOR3F"
   "<ASTRA_SDK_WIGHT_HIGHT>"
   "ASTRA_SDK_WIGHT_HIGHT"
  ))

