(cl:defpackage move_action-msg
  (:use )
  (:export
   "<MOVE_ACTIONACTION>"
   "MOVE_ACTIONACTION"
   "<MOVE_ACTIONACTIONFEEDBACK>"
   "MOVE_ACTIONACTIONFEEDBACK"
   "<MOVE_ACTIONACTIONGOAL>"
   "MOVE_ACTIONACTIONGOAL"
   "<MOVE_ACTIONACTIONRESULT>"
   "MOVE_ACTIONACTIONRESULT"
   "<MOVE_ACTIONFEEDBACK>"
   "MOVE_ACTIONFEEDBACK"
   "<MOVE_ACTIONGOAL>"
   "MOVE_ACTIONGOAL"
   "<MOVE_ACTIONRESULT>"
   "MOVE_ACTIONRESULT"
  ))

