; Auto-generated. Do not edit!


(cl:in-package move_action-msg)


;//! \htmlinclude Move_ActionGoal.msg.html

(cl:defclass <Move_ActionGoal> (roslisp-msg-protocol:ros-message)
  ((num
    :reader num
    :initarg :num
    :type cl:float
    :initform 0.0))
)

(cl:defclass Move_ActionGoal (<Move_ActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Move_ActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Move_ActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move_action-msg:<Move_ActionGoal> is deprecated: use move_action-msg:Move_ActionGoal instead.")))

(cl:ensure-generic-function 'num-val :lambda-list '(m))
(cl:defmethod num-val ((m <Move_ActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_action-msg:num-val is deprecated.  Use move_action-msg:num instead.")
  (num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Move_ActionGoal>) ostream)
  "Serializes a message object of type '<Move_ActionGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'num))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Move_ActionGoal>) istream)
  "Deserializes a message object of type '<Move_ActionGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'num) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Move_ActionGoal>)))
  "Returns string type for a message object of type '<Move_ActionGoal>"
  "move_action/Move_ActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Move_ActionGoal)))
  "Returns string type for a message object of type 'Move_ActionGoal"
  "move_action/Move_ActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Move_ActionGoal>)))
  "Returns md5sum for a message object of type '<Move_ActionGoal>"
  "f942a3e0cbd340847b2a0e5b31a783fe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Move_ActionGoal)))
  "Returns md5sum for a message object of type 'Move_ActionGoal"
  "f942a3e0cbd340847b2a0e5b31a783fe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Move_ActionGoal>)))
  "Returns full string definition for message of type '<Move_ActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#目标值~%float64 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Move_ActionGoal)))
  "Returns full string definition for message of type 'Move_ActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#目标值~%float64 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Move_ActionGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Move_ActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'Move_ActionGoal
    (cl:cons ':num (num msg))
))
