// Generated by gencpp from file move_action/Move_ActionResult.msg
// DO NOT EDIT!


#ifndef MOVE_ACTION_MESSAGE_MOVE_ACTIONRESULT_H
#define MOVE_ACTION_MESSAGE_MOVE_ACTIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_action
{
template <class ContainerAllocator>
struct Move_ActionResult_
{
  typedef Move_ActionResult_<ContainerAllocator> Type;

  Move_ActionResult_()
    : result()  {
    }
  Move_ActionResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::move_action::Move_ActionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_action::Move_ActionResult_<ContainerAllocator> const> ConstPtr;

}; // struct Move_ActionResult_

typedef ::move_action::Move_ActionResult_<std::allocator<void> > Move_ActionResult;

typedef boost::shared_ptr< ::move_action::Move_ActionResult > Move_ActionResultPtr;
typedef boost::shared_ptr< ::move_action::Move_ActionResult const> Move_ActionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_action::Move_ActionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_action::Move_ActionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_action::Move_ActionResult_<ContainerAllocator1> & lhs, const ::move_action::Move_ActionResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_action::Move_ActionResult_<ContainerAllocator1> & lhs, const ::move_action::Move_ActionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::move_action::Move_ActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_action::Move_ActionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_action::Move_ActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_action::Move_ActionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_action::Move_ActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_action::Move_ActionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_action::Move_ActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::move_action::Move_ActionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::move_action::Move_ActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_action/Move_ActionResult";
  }

  static const char* value(const ::move_action::Move_ActionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_action::Move_ActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#最终结果\n"
"string result\n"
;
  }

  static const char* value(const ::move_action::Move_ActionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_action::Move_ActionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Move_ActionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_action::Move_ActionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_action::Move_ActionResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ACTION_MESSAGE_MOVE_ACTIONRESULT_H
