// Generated by gencpp from file move_action/Move_ActionActionGoal.msg
// DO NOT EDIT!


#ifndef MOVE_ACTION_MESSAGE_MOVE_ACTIONACTIONGOAL_H
#define MOVE_ACTION_MESSAGE_MOVE_ACTIONACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <move_action/Move_ActionGoal.h>

namespace move_action
{
template <class ContainerAllocator>
struct Move_ActionActionGoal_
{
  typedef Move_ActionActionGoal_<ContainerAllocator> Type;

  Move_ActionActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  Move_ActionActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::move_action::Move_ActionGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::move_action::Move_ActionActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_action::Move_ActionActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct Move_ActionActionGoal_

typedef ::move_action::Move_ActionActionGoal_<std::allocator<void> > Move_ActionActionGoal;

typedef boost::shared_ptr< ::move_action::Move_ActionActionGoal > Move_ActionActionGoalPtr;
typedef boost::shared_ptr< ::move_action::Move_ActionActionGoal const> Move_ActionActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_action::Move_ActionActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_action::Move_ActionActionGoal_<ContainerAllocator1> & lhs, const ::move_action::Move_ActionActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_action::Move_ActionActionGoal_<ContainerAllocator1> & lhs, const ::move_action::Move_ActionActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_action::Move_ActionActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_action::Move_ActionActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_action::Move_ActionActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2d7c5b5e14813af3d2de17185939102";
  }

  static const char* value(const ::move_action::Move_ActionActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2d7c5b5e14813afULL;
  static const uint64_t static_value2 = 0x3d2de17185939102ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_action/Move_ActionActionGoal";
  }

  static const char* value(const ::move_action::Move_ActionActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"Move_ActionGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: move_action/Move_ActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#目标值\n"
"float64 num\n"
;
  }

  static const char* value(const ::move_action::Move_ActionActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Move_ActionActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_action::Move_ActionActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_action::Move_ActionActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::move_action::Move_ActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ACTION_MESSAGE_MOVE_ACTIONACTIONGOAL_H
