// Generated by gencpp from file move_action/Move_ActionFeedback.msg
// DO NOT EDIT!


#ifndef MOVE_ACTION_MESSAGE_MOVE_ACTIONFEEDBACK_H
#define MOVE_ACTION_MESSAGE_MOVE_ACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_action
{
template <class ContainerAllocator>
struct Move_ActionFeedback_
{
  typedef Move_ActionFeedback_<ContainerAllocator> Type;

  Move_ActionFeedback_()
    : progress_bar(0.0)  {
    }
  Move_ActionFeedback_(const ContainerAllocator& _alloc)
    : progress_bar(0.0)  {
  (void)_alloc;
    }



   typedef double _progress_bar_type;
  _progress_bar_type progress_bar;





  typedef boost::shared_ptr< ::move_action::Move_ActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_action::Move_ActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct Move_ActionFeedback_

typedef ::move_action::Move_ActionFeedback_<std::allocator<void> > Move_ActionFeedback;

typedef boost::shared_ptr< ::move_action::Move_ActionFeedback > Move_ActionFeedbackPtr;
typedef boost::shared_ptr< ::move_action::Move_ActionFeedback const> Move_ActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_action::Move_ActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_action::Move_ActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_action::Move_ActionFeedback_<ContainerAllocator1> & lhs, const ::move_action::Move_ActionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress_bar == rhs.progress_bar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_action::Move_ActionFeedback_<ContainerAllocator1> & lhs, const ::move_action::Move_ActionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::move_action::Move_ActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_action::Move_ActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_action::Move_ActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_action::Move_ActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_action::Move_ActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_action::Move_ActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_action::Move_ActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac7532a8a8f0d2be4f5284d94fee2d59";
  }

  static const char* value(const ::move_action::Move_ActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac7532a8a8f0d2beULL;
  static const uint64_t static_value2 = 0x4f5284d94fee2d59ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_action::Move_ActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_action/Move_ActionFeedback";
  }

  static const char* value(const ::move_action::Move_ActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_action::Move_ActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#连续反馈\n"
"float64 progress_bar\n"
;
  }

  static const char* value(const ::move_action::Move_ActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_action::Move_ActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress_bar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Move_ActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_action::Move_ActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_action::Move_ActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress_bar: ";
    Printer<double>::stream(s, indent + "  ", v.progress_bar);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ACTION_MESSAGE_MOVE_ACTIONFEEDBACK_H
