// Generated by gencpp from file move_action/Move_ActionGoal.msg
// DO NOT EDIT!


#ifndef MOVE_ACTION_MESSAGE_MOVE_ACTIONGOAL_H
#define MOVE_ACTION_MESSAGE_MOVE_ACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_action
{
template <class ContainerAllocator>
struct Move_ActionGoal_
{
  typedef Move_ActionGoal_<ContainerAllocator> Type;

  Move_ActionGoal_()
    : num(0.0)  {
    }
  Move_ActionGoal_(const ContainerAllocator& _alloc)
    : num(0.0)  {
  (void)_alloc;
    }



   typedef double _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::move_action::Move_ActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_action::Move_ActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct Move_ActionGoal_

typedef ::move_action::Move_ActionGoal_<std::allocator<void> > Move_ActionGoal;

typedef boost::shared_ptr< ::move_action::Move_ActionGoal > Move_ActionGoalPtr;
typedef boost::shared_ptr< ::move_action::Move_ActionGoal const> Move_ActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_action::Move_ActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_action::Move_ActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_action::Move_ActionGoal_<ContainerAllocator1> & lhs, const ::move_action::Move_ActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_action::Move_ActionGoal_<ContainerAllocator1> & lhs, const ::move_action::Move_ActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::move_action::Move_ActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_action::Move_ActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_action::Move_ActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_action::Move_ActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_action::Move_ActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_action::Move_ActionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_action::Move_ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f942a3e0cbd340847b2a0e5b31a783fe";
  }

  static const char* value(const ::move_action::Move_ActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf942a3e0cbd34084ULL;
  static const uint64_t static_value2 = 0x7b2a0e5b31a783feULL;
};

template<class ContainerAllocator>
struct DataType< ::move_action::Move_ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_action/Move_ActionGoal";
  }

  static const char* value(const ::move_action::Move_ActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_action::Move_ActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#目标值\n"
"float64 num\n"
;
  }

  static const char* value(const ::move_action::Move_ActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_action::Move_ActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Move_ActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_action::Move_ActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_action::Move_ActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<double>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ACTION_MESSAGE_MOVE_ACTIONGOAL_H
