// Generated by gencpp from file tarkbot_robot/Light_Set.msg
// DO NOT EDIT!


#ifndef TARKBOT_ROBOT_MESSAGE_LIGHT_SET_H
#define TARKBOT_ROBOT_MESSAGE_LIGHT_SET_H

#include <ros/service_traits.h>


#include <tarkbot_robot/Light_SetRequest.h>
#include <tarkbot_robot/Light_SetResponse.h>


namespace tarkbot_robot
{

struct Light_Set
{

typedef Light_SetRequest Request;
typedef Light_SetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Light_Set
} // namespace tarkbot_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tarkbot_robot::Light_Set > {
  static const char* value()
  {
    return "cfc723b899523d9fb55d7d41b0cedf61";
  }

  static const char* value(const ::tarkbot_robot::Light_Set&) { return value(); }
};

template<>
struct DataType< ::tarkbot_robot::Light_Set > {
  static const char* value()
  {
    return "tarkbot_robot/Light_Set";
  }

  static const char* value(const ::tarkbot_robot::Light_Set&) { return value(); }
};


// service_traits::MD5Sum< ::tarkbot_robot::Light_SetRequest> should match
// service_traits::MD5Sum< ::tarkbot_robot::Light_Set >
template<>
struct MD5Sum< ::tarkbot_robot::Light_SetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tarkbot_robot::Light_Set >::value();
  }
  static const char* value(const ::tarkbot_robot::Light_SetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tarkbot_robot::Light_SetRequest> should match
// service_traits::DataType< ::tarkbot_robot::Light_Set >
template<>
struct DataType< ::tarkbot_robot::Light_SetRequest>
{
  static const char* value()
  {
    return DataType< ::tarkbot_robot::Light_Set >::value();
  }
  static const char* value(const ::tarkbot_robot::Light_SetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tarkbot_robot::Light_SetResponse> should match
// service_traits::MD5Sum< ::tarkbot_robot::Light_Set >
template<>
struct MD5Sum< ::tarkbot_robot::Light_SetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tarkbot_robot::Light_Set >::value();
  }
  static const char* value(const ::tarkbot_robot::Light_SetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tarkbot_robot::Light_SetResponse> should match
// service_traits::DataType< ::tarkbot_robot::Light_Set >
template<>
struct DataType< ::tarkbot_robot::Light_SetResponse>
{
  static const char* value()
  {
    return DataType< ::tarkbot_robot::Light_Set >::value();
  }
  static const char* value(const ::tarkbot_robot::Light_SetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TARKBOT_ROBOT_MESSAGE_LIGHT_SET_H
