// Generated by gencpp from file tarkbot_yolov5/ObjectArray.msg
// DO NOT EDIT!


#ifndef TARKBOT_YOLOV5_MESSAGE_OBJECTARRAY_H
#define TARKBOT_YOLOV5_MESSAGE_OBJECTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tarkbot_yolov5/Object.h>

namespace tarkbot_yolov5
{
template <class ContainerAllocator>
struct ObjectArray_
{
  typedef ObjectArray_<ContainerAllocator> Type;

  ObjectArray_()
    : data()  {
    }
  ObjectArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tarkbot_yolov5::Object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tarkbot_yolov5::Object_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectArray_

typedef ::tarkbot_yolov5::ObjectArray_<std::allocator<void> > ObjectArray;

typedef boost::shared_ptr< ::tarkbot_yolov5::ObjectArray > ObjectArrayPtr;
typedef boost::shared_ptr< ::tarkbot_yolov5::ObjectArray const> ObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator1> & lhs, const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator1> & lhs, const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tarkbot_yolov5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c74c52b301e4b25679f3941c4f6f23f";
  }

  static const char* value(const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c74c52b301e4b25ULL;
  static const uint64_t static_value2 = 0x679f3941c4f6f23fULL;
};

template<class ContainerAllocator>
struct DataType< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tarkbot_yolov5/ObjectArray";
  }

  static const char* value(const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tarkbot_yolov5/Object[] data\n"
"\n"
"================================================================================\n"
"MSG: tarkbot_yolov5/Object\n"
"string frame_id\n"
"time stamp\n"
"float32 scores\n"
"float32 ptx\n"
"float32 pty\n"
"float32 distw\n"
"float32 disth\n"
"float32 centerx\n"
"float32 centery\n"
;
  }

  static const char* value(const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tarkbot_yolov5::ObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tarkbot_yolov5::ObjectArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tarkbot_yolov5::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TARKBOT_YOLOV5_MESSAGE_OBJECTARRAY_H
