// Generated by gencpp from file skeleton_follow/astra_sdk_joint.msg
// DO NOT EDIT!


#ifndef SKELETON_FOLLOW_MESSAGE_ASTRA_SDK_JOINT_H
#define SKELETON_FOLLOW_MESSAGE_ASTRA_SDK_JOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <skeleton_follow/astra_sdk_vector2f.h>
#include <skeleton_follow/astra_sdk_vector3f.h>

namespace skeleton_follow
{
template <class ContainerAllocator>
struct astra_sdk_joint_
{
  typedef astra_sdk_joint_<ContainerAllocator> Type;

  astra_sdk_joint_()
    : type(0)
    , depthPosition()
    , worldPosition()  {
    }
  astra_sdk_joint_(const ContainerAllocator& _alloc)
    : type(0)
    , depthPosition(_alloc)
    , worldPosition(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef  ::skeleton_follow::astra_sdk_vector2f_<ContainerAllocator>  _depthPosition_type;
  _depthPosition_type depthPosition;

   typedef  ::skeleton_follow::astra_sdk_vector3f_<ContainerAllocator>  _worldPosition_type;
  _worldPosition_type worldPosition;





  typedef boost::shared_ptr< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> const> ConstPtr;

}; // struct astra_sdk_joint_

typedef ::skeleton_follow::astra_sdk_joint_<std::allocator<void> > astra_sdk_joint;

typedef boost::shared_ptr< ::skeleton_follow::astra_sdk_joint > astra_sdk_jointPtr;
typedef boost::shared_ptr< ::skeleton_follow::astra_sdk_joint const> astra_sdk_jointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator1> & lhs, const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.depthPosition == rhs.depthPosition &&
    lhs.worldPosition == rhs.worldPosition;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator1> & lhs, const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skeleton_follow

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4de40bc4d9da2df315d3755d4261051";
  }

  static const char* value(const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4de40bc4d9da2dfULL;
  static const uint64_t static_value2 = 0x315d3755d4261051ULL;
};

template<class ContainerAllocator>
struct DataType< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skeleton_follow/astra_sdk_joint";
  }

  static const char* value(const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 type\n"
"astra_sdk_vector2f depthPosition\n"
"astra_sdk_vector3f worldPosition\n"
"================================================================================\n"
"MSG: skeleton_follow/astra_sdk_vector2f\n"
"float32 x\n"
"float32 y\n"
"================================================================================\n"
"MSG: skeleton_follow/astra_sdk_vector3f\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.depthPosition);
      stream.next(m.worldPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct astra_sdk_joint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skeleton_follow::astra_sdk_joint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skeleton_follow::astra_sdk_joint_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "depthPosition: ";
    s << std::endl;
    Printer< ::skeleton_follow::astra_sdk_vector2f_<ContainerAllocator> >::stream(s, indent + "  ", v.depthPosition);
    s << indent << "worldPosition: ";
    s << std::endl;
    Printer< ::skeleton_follow::astra_sdk_vector3f_<ContainerAllocator> >::stream(s, indent + "  ", v.worldPosition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKELETON_FOLLOW_MESSAGE_ASTRA_SDK_JOINT_H
