// Generated by gencpp from file skeleton_follow/astra_sdk_wight_hight.msg
// DO NOT EDIT!


#ifndef SKELETON_FOLLOW_MESSAGE_ASTRA_SDK_WIGHT_HIGHT_H
#define SKELETON_FOLLOW_MESSAGE_ASTRA_SDK_WIGHT_HIGHT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace skeleton_follow
{
template <class ContainerAllocator>
struct astra_sdk_wight_hight_
{
  typedef astra_sdk_wight_hight_<ContainerAllocator> Type;

  astra_sdk_wight_hight_()
    : width_l(0)
    , width_r(0)
    , height_t(0)
    , height_b(0)  {
    }
  astra_sdk_wight_hight_(const ContainerAllocator& _alloc)
    : width_l(0)
    , width_r(0)
    , height_t(0)
    , height_b(0)  {
  (void)_alloc;
    }



   typedef int32_t _width_l_type;
  _width_l_type width_l;

   typedef int32_t _width_r_type;
  _width_r_type width_r;

   typedef int32_t _height_t_type;
  _height_t_type height_t;

   typedef int32_t _height_b_type;
  _height_b_type height_b;





  typedef boost::shared_ptr< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> const> ConstPtr;

}; // struct astra_sdk_wight_hight_

typedef ::skeleton_follow::astra_sdk_wight_hight_<std::allocator<void> > astra_sdk_wight_hight;

typedef boost::shared_ptr< ::skeleton_follow::astra_sdk_wight_hight > astra_sdk_wight_hightPtr;
typedef boost::shared_ptr< ::skeleton_follow::astra_sdk_wight_hight const> astra_sdk_wight_hightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator1> & lhs, const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator2> & rhs)
{
  return lhs.width_l == rhs.width_l &&
    lhs.width_r == rhs.width_r &&
    lhs.height_t == rhs.height_t &&
    lhs.height_b == rhs.height_b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator1> & lhs, const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace skeleton_follow

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4642cd8cf102c212293540c01a4443bd";
  }

  static const char* value(const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4642cd8cf102c212ULL;
  static const uint64_t static_value2 = 0x293540c01a4443bdULL;
};

template<class ContainerAllocator>
struct DataType< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skeleton_follow/astra_sdk_wight_hight";
  }

  static const char* value(const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 width_l\n"
"int32 width_r\n"
"int32 height_t\n"
"int32 height_b\n"
;
  }

  static const char* value(const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width_l);
      stream.next(m.width_r);
      stream.next(m.height_t);
      stream.next(m.height_b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct astra_sdk_wight_hight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skeleton_follow::astra_sdk_wight_hight_<ContainerAllocator>& v)
  {
    s << indent << "width_l: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width_l);
    s << indent << "width_r: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width_r);
    s << indent << "height_t: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height_t);
    s << indent << "height_b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height_b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKELETON_FOLLOW_MESSAGE_ASTRA_SDK_WIGHT_HIGHT_H
